name: Daily Steam Check

# Lên lịch: 0h00 UTC-7 → tương đương 07:00 UTC
on:
  schedule:
    - cron: '0 7 * * *' # chạy mỗi ngày 07:00 UTC (~0h00 UTC-7)
  workflow_dispatch:   # cho phép trigger thủ công

jobs:
  daily-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài Java 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Build bot
      - name: Build project
        run: ./mvnw clean

      # 4. Run Notifier
      - name:  Run Discord Notifier
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          LOG_PATH: "./logs/log.txt"
        run: |
          java -cp target/DiscordBot.jar Main
